# Start from the same base image
FROM golang:1.19 AS builder

# Set the working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Copy the source from the current directory to the working directory inside the container
COPY . .

# Build the application with debugging flags
RUN go test -gcflags "all=-N -l" -o /realchat

# Default command to run the dlv debugger on the test binary
CMD ["dlv", "test", "github.com/cassiozareck/realchat/chat", "--listen=:2345", "--headless", "--api-version=2", "--accept-multiclient"]
