version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: cassio
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: realchat
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres


volumes:
  postgres-db:
