version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  test:
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
  debug:
    ports:
      - "2345:2345"
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    build:
      context: .
      dockerfile: Dockerfile.debug
    depends_on:
      - postgres
  test_debug:
    ports:
      - "2345:2345"
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    build:
      context: .
      dockerfile: Dockerfile.test_debug
    depends_on:
      - postgres

volumes:
  postgres-db:
