# Start from the same base image
FROM golang:1.19 AS builder

# Set the working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the working directory inside the container
COPY . .

# Run tests
CMD ["go", "test", "-v", "./..."]
